---
title: "Collaboration_Final"
author: "Dream team"
date: "05/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggraph)
library(billboard)
library(genius)
library(geniusr)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(tibble)
library(tidygraph)
library(textclean)
library(tidytext)
library(graphlayouts)
library(igraph)
library(data.table)
library(plyr)
```

Fetch All Data
#Fetched DATA
```{r}
colaboration_data <- readRDS("colaboration_data.rds")
```

# Converted 
```{r}
colaboration_data_tbl <- as_tbl_graph(colaboration_data, directed = FALSE)
```

# Community Detection
```{r}
colab_detect <- colaboration_data_tbl %>%
  mutate(comm_detec = group_louvain(),
         degree_cen = centrality_degree(mode = "all") ,
         degree_betw = centrality_betweenness())

colab_detect_igraph <- as.igraph(colab_detect)
```
# What are the most featured genres in the respective years?
```{r}
years <- colaboration_data %>%
  distinct(year) %>%
  select(year)

genre_per_year <- colaboration_data %>%
  group_by(year, genre) %>%
  tally() %>%
  select(year, genre, n)

ggplot(genre_per_year, aes(x = year, y = n, color = genre), color = "blue") + geom_point(stat = "identity") + theme(axis.text.x = element_text(angle = 90))
```

LAST STEP
```{r}
write.graph(colab_detect_igraph, "~/Desktop/Billboard_Colab.graphml", format=c("graphml"))
```