---
title: "Pulling New Data"
author: "Group 1"
date: "02/09/2019"
output: html_document
---

## Packages
```{r}
pacman::p_load(billboard, rvest, genius, tidyverse, Rspotify)
```

## Rspotify Auth
```{r}
my_oauth <- spotifyOAuth(app_id="top 100",client_id="75bef91a403c4b17aa946057d97a8330",client_secret="7b192036284f4255a510cdd2ea48f7d0")
```

## Get Data and merge with current
```{r}
data(lyrics, package="billboard")
data(wiki_hot_100s,  package="billboard") 

lyrics_only <- lyrics %>%
  select(lyrics)

ranked_data <- wiki_hot_100s %>%
  cbind(lyrics_only)

url_2017 <- "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2017"
url_2018 <- "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2018"

top_100_2017 <- url_2017 %>%
  read_html() %>%
  html_nodes(xpath='//*[@id="mw-content-text"]/div/table') %>%
  html_table()
top_100_2017 <- top_100_2017[[1]]

top_100_2018 <- url_2018 %>%
  read_html() %>%
  html_nodes(xpath='//*[@id="mw-content-text"]/div/table') %>%
  html_table()
top_100_2018 <- top_100_2018[[1]]

top_100_2017['Year'] <- 2017
top_100_2018['Year'] <- 2018

colnames(top_100_2017) <- c("no", "title", "artist", "year")
colnames(top_100_2018) <- c("no", "title", "artist", "year")

top_100_2017[] <- lapply(top_100_2017, gsub, pattern='"', replacement='')
top_100_2018[] <- lapply(top_100_2018, gsub, pattern='"', replacement='')

top_100_2017$lyrics <- NA
top_100_2018$lyrics <- NA

new_df  <- rbind(top_100_2017, top_100_2018)
df_all_no_lyrics <- rbind(ranked_data, new_df)
```

## Lyrics that are not found
```{r}
na_lyrics <- df_all_no_lyrics %>%
  filter(is.na(df_all_no_lyrics$lyrics))
lyric_no_NA <- na.omit(df_all_no_lyrics)
```

## Add lyrics to NA
```{r}
datalist <- list()
for (row in 1:nrow(na_lyrics)) {
  print(row)
  x <- possible_lyrics(artist = str_remove_all(na_lyrics[3]$artist[row], '"'), song = str_remove_all(na_lyrics[2]$title[row], '"'), info = "simple")
  if (grepl("featuring", na_lyrics[3]$artist[row])) {
    z <- gsub("featuring.*","",na_lyrics[3]$artist[row])
    x <- possible_lyrics(artist = substr(z, 1, nchar(z)-1), song = str_remove_all(na_lyrics[2]$title[row], '"'), info = "simple")
    if (length(x) == 0) {
      datalist[[row]] <- NA
    }else {
      datalist[[row]] <- x %>%
          summarise(lyrics = paste(lyric, collapse=", "))
    }
  }else if (length(x) != 0){
    datalist[[row]] <- x %>%
        summarise(lyrics = paste(lyric, collapse=", "))
  }else {
    datalist[[row]] <- NA
  }
}
lyrics_data = do.call(rbind, datalist)
na_lyrics$lyrics <- lyrics_data
```

```{r}
lyrics_added <- rbind(lyric_no_NA, na_lyrics)
# saveRDS(lyrics_added, file = "data_in/all_data_lyrics.rds")
all_data_lyrics <- readRDS("data_in/all_data_lyrics.rds")
```

GENRE
```{r}
artist_genre <- list()
for (row in 1:nrow(top_100_2017)) {
  print(row)
  if (row == 4627 | row == 4626 | row == 4628) {
    next
  }
  if (grepl("featuring", top_100_2017[[3]][row])) {
    
    z <- gsub("featuring.*","",top_100_2017[[3]][row])
    genre <- searchArtist(substr(z, 1, nchar(z)-1), token = my_oauth)[5]$genres[1]
    
    if (is.null(genre)) {
      if (grepl("and", top_100_2017[[3]][row])) {
        
        x <- gsub(" and.*","",top_100_2017[[3]][row])
        x[] <- lapply(x, gsub, pattern='"', replacement='')
        genre <- searchArtist(x[[1]], token = my_oauth)[5]$genres[1]
        
        if (is.null(genre)) {
          artist_genre[[row]] <- NA
        }else {
          artist_genre[[row]] <- sub("\\,.*", "", genre)
        }
        
      }else{
        artist_genre[[row]] <- NA
      }
    }else {
      artist_genre[[row]] <- sub("\\,.*", "", genre)
    }
    
  }else if (grepl("and", top_100_2017[[3]][row])) {
    
    x <- gsub(" and.*","",top_100_2017[[3]][row])
    x[] <- lapply(x, gsub, pattern='"', replacement='')
    genre <- searchArtist(x[[1]], token = my_oauth)[5]$genres[1]
    if (is.null(genre)) {
      artist_genre[[row]] <- NA
    }else {
      artist_genre[[row]] <- sub("\\,.*", "", genre)
    }
    
  }else {
    
    genre <- searchArtist(top_100_2017[[3]][row],token = my_oauth)[5]$genres[1]
    if (is.null(genre)) {
      artist_genre[[row]] <- NA
    }else {
      artist_genre[[row]] <- sub("\\,.*", "", genre)
    } 
    
  }
}
genre_data <- do.call(rbind, artist_genre)
data_with_genre <- cbind(lyrics_added, genre_data) # 4627
# saveRDS(data_with_genre, 'all_data_genre_not_generalised.rds')
```

```{r}
all_data_genre_ungen <- readRDS("all_data_genre_not_generalised.rds")
```

```{# r}
k <- all_data_genre_ungen %>%
  distinct(genre_data)

`%notin%` <- Negate(`%in%`)

d <- k %>% filter(genre_data %notin% all)

```

```{r}
pop <- c('dance pop', 'pop', 'pop christmas', 'post-teen pop', 'new wave pop', 'brill building pop', 'bubblegum pop', 'canadian pop', 'boy band', 'europop', 'viral pop', 'synthpop', 'pop punk', 'canadian hip hop', 'afropop', 'classic girl group', 'girl group', 'australian dance', 'k-hop')

rap <- c('pop rap', 'rap', 'southern hip hop', 'hip hop', 'trap music', 'dirty south rap', 'gangster rap', 'east coast hip hop', 'hardcore hip hop', 'hip pop', 'hip house', 'rap metal', 'dwn trap', 'emo rap')

rock <- c('mellow gold', 'soft rock', 'rock', 'album rock', 'pop rock', 'classic rock', 'folk rock', 'hard rock', 'dance rock', 'roots rock', 'southern rock', 'blues-rock', 'alternative rock', 'funk rock', 'psychedelic rock', 'rock-and-roll', 'modern rock', 'art rock', 'classic funk rock', 'adult standards', 'rockabilly', 'merseybeat', 'surf music', 'deep adult standards', 'rhythm and blues', 'louisiana blues', 'blues', 'melodic metalcore', 'glam metal', 'alternative metal', 'comic metal', 'nu metal')

electronic <- c('tropical house', 'edm', 'brostep', 'bmore', 'broken beat', 'dark trap', 'deep groove house', 'retro electro', 'drum and bass', 'italian techno', 'electronic', 'dubstep', 'finnish electro', 'complextro', 'house', 'cyberpunk', 'electro')

r_and_b <- c('r&b', 'urban contemporary', 'deep pop r&b', 'indie r&b', 'doo-wop', 'modern reggae', 'easy listening', 'reggae', 'uk reggae')

soul  <- c('motown', 'disco', 'soul', 'funk', 'neo soul', 'soul christmas', 'new jack swing', 'memphis soul', 'chicago soul', 'southern soul', 'soul blues', 'post-disco', 'quiet storm', 'jazz blues', 'jazz funk', 'electric blues', 'latin', 'christian relaxative', 'memphis soul', 'classic soul', 'indie jazz', 'bebop', 'dixieland', 'avant-garde jazz', 'jazz trumpet', 'smooth jazz', 'classical')

country <- c('country',' contemporary country', 'country christmas', 'country road', 'modern country rock', 'country rock', 'traditional country', 'folk christmas', 'folk', 'folk-pop', 'nashville sound', 'country dawn', 'traditional folk', 'outlaw country', 'country gospel','arkansas country', 'american folk revival', 'alabama indie', 'london indie', 'alaska indie')

other <- c('beach music', 'background music', 'rif', 'disney', 'chillwave', 'comic', 'british invasion', 'compositional ambient', 'canadian celtic')

all_data <- all_data_genre_ungen

all_data$genre <- ifelse(grepl(paste(pop, collapse = "|"), all_data$genre_data), "pop",
             ifelse(grepl(paste(rap, collapse = "|"), all_data$genre_data), "rap",
             ifelse(grepl(paste(rock, collapse = "|"), all_data$genre_data), "rock",
             ifelse(grepl(paste(electronic, collapse = "|"), all_data$genre_data), "electronic",
             ifelse(grepl(paste(r_and_b, collapse = "|"), all_data$genre_data), "r&b",
             ifelse(grepl(paste(soul, collapse = "|"), all_data$genre_data), "soul",
             ifelse(grepl(paste(other, collapse = "|"), all_data$genre_data), "other",      
             ifelse(grepl(paste(country, collapse = "|"), all_data$genre_data), "country", "other"))))))))
all_data$genre_data <- NULL


#   saveRDS(all_data, file = "data_in/all_data.rds")
```


TESTING
```{# r}
datalist_2017 = list()
awe <- list()
for (row in 1:nrow(top_100_2017)) {
  print(row)
  x <- possible_lyrics(artist = str_remove_all(top_100_2017[3]$artist[row], '"'), song = str_remove_all(top_100_2017[2]$title[row], '"'), info = "simple")
  awe[[row]] <- searchArtist(top_100_2017[3]$artist[row],token = my_oauth)$genres[1]
  if (grepl("featuring", top_100_2017[3]$artist[row])) {
    z <- gsub("featuring.*","",top_100_2017[3]$artist[row])
    x <- possible_lyrics(artist = substr(z, 1, nchar(z)-1), song = str_remove_all(top_100_2017[2]$title[row], '"'), info = "simple")
    awe[[row]] <- searchArtist(top_100_2017[3]$artist[row],token = my_oauth)$genres[1]
    if (length(x) == 0) {
      datalist_2017[[row]] <- NA
      awe[[row]] <- NA
    }else {
      datalist_2017[[row]] <- x %>%
          summarise(lyrics = paste(lyric, collapse=", "))
      awe[[row]] <- searchArtist(top_100_2017[3]$artist[row],token = my_oauth)$genres[1]
    }
  }else if (length(x) != 0){
    datalist_2017[[row]] <- x %>%
        summarise(lyrics = paste(lyric, collapse=", "))
    awe[[row]] <- searchArtist(top_100_2017[3]$artist[row],token = my_oauth)$genres[1]
  }else {
    datalist_2017[[row]] <- NA
    awe[[row]] <- NA
  }
}
lyrics_data_2017 = do.call(rbind, datalist_2017)
genre_data_2017 = do.call(rbind, awe)
top_100_2017$lyrics <- lyrics_data_2017
```
