---
title: "test"
author: "Group 1"
date: "03/09/2019"
output: html_document
---

```{r setup, include=FALSE}
pacman::p_load(spotifyr, tidygraph, billboard, Rspotify, dplyr, ggplot2, igraph, ggraph, tidyverse,tibble, graphlayouts)
```

```{r}
client_id = Sys.setenv(SPOTIFY_CLIENT_ID = 'a1ab0e500cd84b2ab336c6a4eb2b3b29')
client_secret = Sys.setenv(SPOTIFY_CLIENT_SECRET = '471f70c3e1c74ed8b75ea23656b8481c')
token <- get_spotify_access_token()

playlist <- get_playlist('37IRJrV9jd0LnsFTIY83ax', fields = c("tracks.items.track.artists.name", "tracks.items.track.name"), authorization = token) %>%
  as.data.frame()

all_fields <- get_playlist('37IRJrV9jd0LnsFTIY83ax', fields = NULL, authorization = token)


```

```{r}
data(lyrics, package='billboard')
data(wiki_hot_100s, package = 'billboard')
data(spotify_track_data, package = 'billboard')

original <- as.data.frame(lyrics)

test_graph <- as_tbl_graph(lyrics) %>%
  convert(to_directed) %>%
  mutate(labels = group_label_prop(),
         cent_d = centrality_degree(mode = "all"),
         cent_out = centrality_degree(mode = "out"),
         cent_in = centrality_degree(mode = "in"),
         cent_bwtn = centrality_betweenness()) %>%
  rename('title' = name) %>%
  as.data.frame()

new_graph <- original %>%
  left_join(test_graph, by = "title") %>%
  select(title, artist, year, lyrics, labels, cent_d, cent_out, cent_in, cent_bwtn)

track_data <- spotify_track_data %>%
  rename("title" = track_name)

experimental_graph <- new_graph %>%
  left_join(track_data, by = "title")

test_graph <- wiki_hot_100s %>%
  select(no) %>%
  cbind(new_graph) %>%
  rename("rank" = no)

elvis_filter <- test_graph %>%
  select(artist, title) %>%
  group_by(artist) %>%
  filter(artist == "Elvis Presley")

elvis <- as_tbl_graph(elvis_filter)
elvis %>%
  #filter(name == "Elvis Presley") %>%
  ggraph(layout = 'stress') + 
    geom_edge_link() + 
    geom_node_point(size = 8, colour = 'steelblue') +
    geom_node_text(aes(label = name), colour = 'black', vjust = 0.4) + 
    ggtitle('Binding graphs') + 
    theme_graph()

frequent_artists <- test_graph %>%
  select(artist, title) %>%
  group_by(artist) %>%
  as_tbl_graph(directed = T) %>%
  activate(nodes) %>%
  mutate(deg = centrality_degree(mode = "all")) %>%
  filter(deg > 15)

frequent_artists %>%
  ggraph(layout = 'stress') + 
    geom_edge_link() + 
    geom_node_point(size = 8, colour = 'steelblue') +
    geom_node_text(aes(label = name), colour = 'black', vjust = 0.4) + 
    ggtitle('Frequent Artists') + 
    theme_graph()

featuring_artist_feat <-str_split_fixed(new_graph$artist, "featuring", 2)

featuring_artist_feat <- as.data.frame(featuring_artist_feat)
  
featuring_artist_comma <- str_split_fixed(featuring_artist_feat$V2,",",2)


featuring_artist_comma <- as.data.frame(featuring_artist_comma)

featuring_artist_and <- str_split_fixed(featuring_artist_comma$V2, "and",2)

featuring_artist_and <- as.data.frame(featuring_artist_and)

featuring_artist_feat$V2 <- NULL
featuring_artist_and$V2 <- NULL
featuring_artist_comma$V2 <- NULL



feature_total <- cbind(featuring_artist_feat,featuring_artist_comma)%>%
  cbind(featuring_artist_and)%>%
  cbind(lyrics)

names(feature_total)[1] <- "Artist_1"
names(feature_total)[2] <- "Artist_2"
names(feature_total)[3] <- "Artist_3"
names(feature_total)[4] <- "Artist_4"

feature_total$artist <- NULL

feature_total_select <- feature_total%>%
  select(Artist_1,Artist_2,Artist_3,Artist_4,title)

tidyr::gather(feature_total, "artist", "n", 2:4)

    
feature_total$V2 <- NULL

feature_total <- feature_total%>%
  as_tbl_graph()%>%
  as.igraph()
  #str_split_fixed(featuring_artists_og$V2, "and", 2)%>%
  #as.data.frame(featuring_artists_og)%>%
  #cbind(new_graph,featuring_artists_og)%>%
  #filter(V2 != "")


 find <- gsub("featuring.*","",top_100_2017[[3]][row])
genre <- searchArtist(substr(z, 1, nchar(z)-1), token = my_oauth)[5]$genres[1]

featuring_artists_extra <- new_graph%>%
  ffilter(str_detect(artist," (featuring.*[a-z]+,)(.* and) (.*)"))
  
all_data <- readRDS("data_in/all_data.rds")

awe <- all_data %>%
  select(artist, title) %>%
  as_tbl_graph() %>%
  activate(nodes) %>%
  convert(to_undirected) %>%
  mutate(comm = group_louvain(),
         degree_cent = centrality_degree(mode = "all"),
         degree_in = centrality_degree(mode = "in"),
         degree_out = centrality_degree(mode = "out"),
         eigen = centrality_eigen()) %>%
  convert(to_directed) %>%
  rename("artist" = name) %>%
  as.data.frame()
# 
final <- all_data %>%
  left_join(awe, by = "artist")

comms <- final %>%
  group_by(comm)
```


